default: &default
  adapter: mysql2
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: xfera
  password:
  host: 127.0.0.1 #(MYSQL DB running in a container)

development:
  <<: *default
  database: searching_norris_2_development

test:
  <<: *default
  database: searching_norris_2_test

production:
  <<: *default
  database: searching_norris_2_production
  username: searching_norris_2
  password: <%= ENV['SEARCHING_NORRIS_2_DATABASE_PASSWORD'] %>
