default: &default
  adapter:  postgresql
  encoding: unicode
  pool:     <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

  host:     <%= ENV.fetch("DATABASE_HOST") { "localhost" } %>
  port:     <%= ENV.fetch("DATABASE_PORT") { "5432" } %>
  username: <%= ENV.fetch("DATABASE_USERNAME") { "don" } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "don" } %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME") { "restarone_development" } %>

test:
  <<: *default
  database:  <%= ENV.fetch("DATABASE_NAME") { "restarone_test" } %>

production:
  <<: *default
  database:  <%= ENV.fetch("DATABASE_NAME") { "restarone" } %>